name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: true
        update-environment: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH="${{ github.workspace }}"
        pytest

    - name: Build Docker image with SHA and latest tags
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ramyamo/fruits-api:${IMAGE_TAG} -t ramyamo/fruits-api:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker images (SHA and latest)
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push ramyamo/fruits-api:${IMAGE_TAG}
        docker push ramyamo/fruits-api:latest
